### PR TITLE
fix whereValue types

### PR DESCRIPTION
**Pull request by gregwebs**
Dictionary<any> was ruining type inference
The new type of <W, T extends W>
is more exact and does not mess up inference

### CODE REVIEW

**Comment by bczengel** [comment]
These changes are great!!  Thanks for the help!!  I merge them just as soon as I get a chance.  If you have time between now and then, would you mind taking a spin through the tests and updating the references to `LoDash.` to `_.`?  If not I'll take care of it after I do the merge.

**Comment by gregwebs** [comment]
What is left now? This is working great for us. Are you going to send a pull request now?

**Comment by bczengel** [comment]
I have to finish all the chainable methods and get the object chainables to
be available for arrays as well.

**Comment by gregwebs** [comment]
ah, I don't use chaining. Are there just functions that are missing? As long as you aren't preventing a user's code from compiling this should get pull requested. Perhaps you may need a few any types right now until you get a chance to finish chaining?

**Comment by georgiosd** [comment]
Hey guys, good work. I look forward to the final release so I can give it a go :)

**Comment by gregwebs** [comment]
@georgiosd do you use chaining? If not, it is ready for you. If you do, you should be able to use the underscore bindings.

**Comment by georgiosd** [comment]
I do use chaining but not always, depends on the operation - it's mixed. I'll just wait, no biggie.

**Pull request merged**
